before_script:
  - echo "xdebug.mode=off" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer

language: php

php:
  - 7.4
  - 8.0
  - 8.1

install:
  - composer update --prefer-lowest
  - composer update

notifications:
  email: false

script:
  - composer lint
  - composer analyse
